### ISSUE TITLE
Allow wider timeline

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#10]
The current logic is optimised to just support date ranges of one day.

The capability would be more useful if we could use ranges greater than, or less than one day.

The logic would be:
* provide all serials and participations where the serial finishes after the start parameter AND starts before the end parameter

The above logic allows for serials that overlap the start/end times.

**Comment by rnllv** [comment]
>provide all serials and participations where the serial finishes after the start parameter AND starts before the end parameter

1. We'll be considering only the serials. Participations are expected to be within the serial.

2. I'm not sure if I understood this, and I believe this would be a confusing user experience if the query returns based on the below where clause
```SQL
where serial.end>ui_input_start_time and serial.start<ui_input_end_time
```

I believe the filter should fetch all serials whose start and end are within the parameter start and end times.

**Comment by IanMayo** [comment]
Yes - the start and end filters can be counter-intuitive.  What it returns is any serials that have some activity during that period.

So, if they ask for a 24 hour period, but that's within a 3-day serial, then that serial should be returned, because there is activity in the period of interest that they may need to know is happening.

If it does end up with user confusion we can switch to the more literal interpretation.

**Comment by rnllv** [comment]
>So, if they ask for a 24 hour period, but that's within a 3-day serial, then that serial should be returned, because there is activity in the period of interest that they may need to know is happening.

Then the simplest way would be to discard the end date. The filters should fetch all serials which have a start date between the 2 UI input filter dates. The UI can sport something like: "Fetch all Serials starting between 2020-12-01 and 2021-02-01"

This would also be less confusing to the users.

**Comment by IanMayo** [comment]
That filter wouldn't return the 3-day serial, since the start date isn't between the start/end dates.

**Comment by rnllv** [comment]
It would based on the filter values and implementation.

Suppose there are 5 serials.
Serial A: Start Time: 2020-12-01 End Time: 2020-12-04 (Serial from 1st to 4th December, 2020)
Serial B: Start Time: 2020-12-01 End Time: 2020-12-01 (Serial starting and ending on 1st December, 2020)
Serial C: Start Time: 2020-12-02 End Time: 2020-12-02 (Serial starting and ending on 2nd December, 2020)
Serial D: Start Time: 2020-12-03 End Time: 2020-12-03 (Serial starting and ending on 3rd December, 2020)
Serial E: Start Time: 2020-12-04 End Time: 2020-12-04 (Serial starting and ending on 4th December, 2020)

1) Let's say the UI passes two dates: 2020-12-01 and 2020-12-03 (which means "Fetch all Serials starting between 2020-12-01 and 2020-12-03), then metadata query will (or can be changed to) fetch Serials A, B, C, and D (since all these start between the two dates)

2) Let's say the UI passes two dates: 2020-12-02 and 2020-12-04 (which means "Fetch all Serials starting between 2020-12-02 and 2020-12-04), then metadata query will (or can be changed to) fetch Serials B, C, D, and E (since all these start between the two dates)

**Comment by IanMayo** [comment]
I think that's my point.  In scenario 2 they won't get Serial A, even though it is "live" for the 2nd, 3rd & 4th of December.

The "finishes after the start, and starts before the end" is the logical way of getting time periods that span the requested dates.

**Comment by rnllv** [comment]
>I think that's my point. In scenario 2 they won't get Serial A, even though it is "live" for the 2nd, 3rd & 4th of December.

Yep, it won't. I was just suggesting this would be the easiest and clearest UI implementation.

>The "finishes after the start, and starts before the end" is the logical way of getting time periods that span the requested dates.

This wouldn't either. This will miss the serials that are ``"completely within"`` the UI start and end filter inputs.

Based on your review comments, I believe what we want is ``Find all serials that "were happening" during the given period``.

This [fiddle here](http://www.sqlfiddle.com/#!17/8ff68/1) will be helpful.

Please confirm.

**Comment by rnllv** [comment]
>This wouldn't either. This will miss the serials that are "completely within" the UI start and end filter inputs.

I'm sorry and I take this back. The approach you suggested should also work for ``Find all serials that "were happening" during the given period``

Here's the [updated sqlfiddle](http://www.sqlfiddle.com/#!17/8ff68/10)

So, shall I proceed with ``--Third version`` for the **dashboard_metadata** query filter?

**Comment by IanMayo** [comment]
Sorted.
